// GENERATED by scripts/sync-blog.mjs — do not edit by hand.
// Slugs of posts the owner wrote in the admin panel, so sitemap.ts can list
// them. Bodies stay in /blog-data/posts.json and are rendered by view.php.
export interface CmsPost { slug: string; date: string }

export const cmsPosts: CmsPost[] = [
  {"slug":"september-october-in-furano-best-autumn-attractions-things-to-do","date":"2026-08-22"},
  {"slug":"hinode-park-lavender-festival-2026-experience-the-magic-of-kamifurano-s-summer-nights","date":"2026-07-03"},
  {"slug":"summer-season-dinner-notice","date":"2026-06-29"},
  {"slug":"best-restaurants-in-furano","date":"2025-05-10"},
  {"slug":"furano-lavender-guide","date":"2025-04-22"},
  {"slug":"halal-food-in-furano","date":"2025-03-15"},
  {"slug":"nepalese-food-guide","date":"2025-02-28"},
  {"slug":"hokkaido-food-guide","date":"2025-01-05"},
  {"slug":"biei-blue-pond-guide","date":"2025-01-20"},
  {"slug":"furano-winter-travel-guide","date":"2024-12-01"},
  {"slug":"furano-family-travel-guide","date":"2024-11-15"},
];
