/**
 * Pull the slugs of the owner's own blog posts into the build.
 *
 * Posts written in the admin panel live only in /blog-data/posts.json. They
 * have no entry in app/lib/blogData.ts and no static page — .htaccess falls
 * back to /blog/view.php for them. They render fine and the blog index links
 * to them, but sitemap.ts was built from blogData.ts alone, so those posts
 * were never submitted to Google.
 *
 * This writes app/lib/cmsPosts.ts (slug + date only — view.php owns the body)
 * so the sitemap can list them. Run it alongside the other two syncs:
 *
 *   node scripts/sync-menu.mjs && node scripts/sync-team.mjs && node scripts/sync-blog.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const URL_ = process.env.BLOG_URL || 'https://www.nepaldining.online/blog-data/posts.json';
const FILE = path.join(process.cwd(), 'app/lib/cmsPosts.ts');

const res = await fetch(URL_, { cache: 'no-store' });
if (!res.ok) throw new Error(`${URL_} → HTTP ${res.status}`);
const live = await res.json();

if (!Array.isArray(live) || live.length === 0) {
  throw new Error('live posts.json is empty — refusing to overwrite cmsPosts.ts');
}

const rows = live
  .filter((p) => p && typeof p.slug === 'string' && p.slug)
  // a slug that is not URL-safe would put a broken entry in the sitemap
  .filter((p) => /^[a-z0-9-]+$/.test(p.slug))
  .map((p) => '  ' + JSON.stringify({
    slug: p.slug,
    date: typeof p.date === 'string' && p.date ? p.date : new Date().toISOString().slice(0, 10),
  }) + ',')
  .join('\n');

const out = `// GENERATED by scripts/sync-blog.mjs — do not edit by hand.
// Slugs of posts the owner wrote in the admin panel, so sitemap.ts can list
// them. Bodies stay in /blog-data/posts.json and are rendered by view.php.
export interface CmsPost { slug: string; date: string }

export const cmsPosts: CmsPost[] = [
${rows}
];
`;

fs.writeFileSync(FILE, out);
console.log(`synced ${live.length} blog slugs from ${URL_}`);
